/**
 * 8ジャンル向けの代表部材・工事単価。
 * 既存シード配列は1件も改変せず、
 * 本ファイルへ追記分だけ定義する。
 */

import type { PriceCostMasterItemSeedV1 } from "./price-cost-master-types-v1.js";
import type { TislyUnifiedGenreV1 } from "../shared/genres/tisly-genres-v1.js";

/** 既存シード ID → 統一ジャンル（上書きではなく付与） */
export const PRICE_COST_MASTER_EXISTING_GENRE_MAP_V1: Record<
  string,
  TislyUnifiedGenreV1
> = {
  "PCM-PART-PH-TX-001": "IOT関連",
  "PCM-PART-PH-ELECTRODE-001": "IOT関連",
  "PCM-PART-RP2350-RS485-001": "IOT関連",
  "PCM-PART-IP65-BOX-001": "電気工事",
  "PCM-SUB-EW-LITE-001": "IOT関連",
  "PCM-SUB-EW-STD-001": "IOT関連",
  "PCM-LAB-SENSOR-PANEL-001": "電気工事",
  "PCM-LAB-VP-SLEEVE-001": "IOT関連",
  "PCM-LAB-CAL-COMMISSION-001": "IOT関連",
};

/** ジャンル別 材料・パーツ（末尾追記用） */
export const PRICE_COST_MASTER_GENRE_PARTS_SEED_V1: PriceCostMasterItemSeedV1[] =
  [
    {
      id: "PCM-PART-VVF-2C-100-001",
      kind: "parts",
      category: "電線",
      genre: "電気工事",
      name: "VVFケーブル 2.0mm²-2C 100m巻",
      costPrice: 4200,
      sellPrice: 7800,
      unitLabel: "巻",
      notes: "屋内配線の標準ケーブル",
      tags: ["VVF", "電気工事", "配線"],
    },
    {
      id: "PCM-PART-SW-BOX-M-001",
      kind: "parts",
      category: "ボックス",
      genre: "電気工事",
      name: "樹脂製スイッチボックス（中型）",
      costPrice: 180,
      sellPrice: 450,
      unitLabel: "個",
      notes: "コンセント・スイッチ用",
      tags: ["ボックス", "電気工事"],
    },
    {
      id: "PCM-PART-CAM-IP5M-001",
      kind: "parts",
      category: "カメラ",
      genre: "防犯カメラ",
      name: "屋外用IPカメラ 500万画素",
      costPrice: 12800,
      sellPrice: 24800,
      unitLabel: "台",
      notes: "PoE給電・赤外線対応",
      tags: ["防犯カメラ", "PoE"],
    },
    {
      id: "PCM-PART-CAM-DOME-POE-001",
      kind: "parts",
      category: "カメラ",
      genre: "防犯カメラ",
      name: "PoE対応ドームカメラ",
      costPrice: 9800,
      sellPrice: 19800,
      unitLabel: "台",
      notes: "店舗・エントランス向け",
      tags: ["防犯カメラ", "ドーム"],
    },
    {
      id: "PCM-PART-POE-SW8-001",
      kind: "parts",
      category: "ネットワーク機器",
      genre: "ネットワーク",
      name: "PoEスイッチ 8ポート",
      costPrice: 8900,
      sellPrice: 16800,
      unitLabel: "台",
      notes: "カメラ・AP給電用",
      tags: ["PoE", "ネットワーク"],
    },
    {
      id: "PCM-PART-LAN-CAT6-100-001",
      kind: "parts",
      category: "LAN部材",
      genre: "ネットワーク",
      name: "LANケーブル Cat6 100m箱",
      costPrice: 3200,
      sellPrice: 6500,
      unitLabel: "箱",
      notes: "屋内LAN配線標準",
      tags: ["LAN", "Cat6", "ネットワーク"],
    },
    {
      id: "PCM-PART-COAX-S5C-100-001",
      kind: "parts",
      category: "TV部材",
      genre: "TV工事",
      name: "同軸ケーブル S-5C-FB 100m",
      costPrice: 3800,
      sellPrice: 7200,
      unitLabel: "巻",
      notes: "BS/CS対応同軸",
      tags: ["同軸", "TV工事"],
    },
    {
      id: "PCM-PART-TV-SPLIT4-001",
      kind: "parts",
      category: "TV部材",
      genre: "TV工事",
      name: "4分配器（CS/BS対応）",
      costPrice: 980,
      sellPrice: 2200,
      unitLabel: "台",
      notes: "宅内TV分配",
      tags: ["分配器", "TV工事"],
    },
    {
      id: "PCM-PART-AC-PIPE-SET-001",
      kind: "parts",
      category: "エアコン部材",
      genre: "エアコン",
      name: "エアコン配管セット 2.5m",
      costPrice: 2800,
      sellPrice: 5800,
      unitLabel: "セット",
      notes: "被覆銅管・ドレンホース込",
      tags: ["エアコン", "配管"],
    },
    {
      id: "PCM-PART-AC-PAIR-20-001",
      kind: "parts",
      category: "エアコン部材",
      genre: "エアコン",
      name: "ペアコイル 2分3分 20m",
      costPrice: 8900,
      sellPrice: 16800,
      unitLabel: "巻",
      notes: "延長配管用",
      tags: ["エアコン", "冷媒管"],
    },
    {
      id: "PCM-PART-DUCT-AL100-001",
      kind: "parts",
      category: "空調部材",
      genre: "空調",
      name: "アルミダクト φ100 10m",
      costPrice: 1600,
      sellPrice: 3500,
      unitLabel: "本",
      notes: "換気・空調分岐用",
      tags: ["空調", "ダクト"],
    },
    {
      id: "PCM-PART-FAN-PIPE-001",
      kind: "parts",
      category: "空調部材",
      genre: "空調",
      name: "パイプ用換気扇（標準）",
      costPrice: 3200,
      sellPrice: 6800,
      unitLabel: "台",
      notes: "トイレ・洗面換気",
      tags: ["空調", "換気扇"],
    },
    {
      id: "PCM-PART-AMP-60W-001",
      kind: "parts",
      category: "音響機器",
      genre: "音響",
      name: "業務用音響アンプ 60W",
      costPrice: 12800,
      sellPrice: 24800,
      unitLabel: "台",
      notes: "店舗BGM・館内放送",
      tags: ["音響", "アンプ"],
    },
    {
      id: "PCM-PART-SP-CEILING-001",
      kind: "parts",
      category: "音響機器",
      genre: "音響",
      name: "天井埋込スピーカー",
      costPrice: 4500,
      sellPrice: 9800,
      unitLabel: "台",
      notes: "店舗・待合向け",
      tags: ["音響", "スピーカー"],
    },
    {
      id: "PCM-PART-ESP32-DEV-001",
      kind: "parts",
      category: "制御ボード",
      genre: "IOT関連",
      name: "ESP32 開発ボード",
      costPrice: 980,
      sellPrice: 2800,
      unitLabel: "枚",
      notes: "Wi-Fi/BLE 現場IoT",
      tags: ["IOT関連", "ESP32"],
    },
    {
      id: "PCM-PART-RP2350-PICO-001",
      kind: "parts",
      category: "制御ボード",
      genre: "IOT関連",
      name: "RP2350 マイコンボード",
      costPrice: 1500,
      sellPrice: 4200,
      unitLabel: "枚",
      notes: "TiSLY エッジ制御向け",
      tags: ["IOT関連", "RP2350"],
    },
  ];

/** ジャンル別 標準工事・作業単価（末尾追記用） */
export const PRICE_COST_MASTER_GENRE_LABOR_SEED_V1: PriceCostMasterItemSeedV1[] =
  [
    {
      id: "PCM-LAB-VVF-10M-001",
      kind: "labor",
      category: "電気工事",
      genre: "電気工事",
      name: "VVF配線工事（10mまで）",
      costPrice: null,
      sellPrice: 18000,
      unitLabel: "式",
      notes: "コンセント増設の標準配線",
      tags: ["電気工事", "VVF", "配線"],
    },
    {
      id: "PCM-LAB-CAM-INSTALL-001",
      kind: "labor",
      category: "防犯カメラ",
      genre: "防犯カメラ",
      name: "防犯カメラ1台取付・調整",
      costPrice: null,
      sellPrice: 15000,
      unitLabel: "台",
      notes: "取付・通信設定・画角調整",
      tags: ["防犯カメラ", "取付"],
    },
    {
      id: "PCM-LAB-LAN-10M-001",
      kind: "labor",
      category: "ネットワーク",
      genre: "ネットワーク",
      name: "LAN配線工事（10m）",
      costPrice: null,
      sellPrice: 8000,
      unitLabel: "式",
      notes: "Cat6 屋内配線・末端処理",
      tags: ["ネットワーク", "LAN", "配線"],
    },
    {
      id: "PCM-LAB-ANTENNA-001",
      kind: "labor",
      category: "TV工事",
      genre: "TV工事",
      name: "TVアンテナ取付工事",
      costPrice: null,
      sellPrice: 25000,
      unitLabel: "式",
      notes: "屋根・破風取付の標準",
      tags: ["TV工事", "アンテナ"],
    },
    {
      id: "PCM-LAB-AC-INSTALL-001",
      kind: "labor",
      category: "エアコン",
      genre: "エアコン",
      name: "ルームエアコン取付工事（標準）",
      costPrice: null,
      sellPrice: 18000,
      unitLabel: "台",
      notes: "配管4mまで・真空引き込",
      tags: ["エアコン", "取付"],
    },
    {
      id: "PCM-LAB-FAN-REPLACE-001",
      kind: "labor",
      category: "空調",
      genre: "空調",
      name: "換気扇取替工事",
      costPrice: null,
      sellPrice: 12000,
      unitLabel: "台",
      notes: "既存穴流用の標準取替",
      tags: ["空調", "換気扇"],
    },
    {
      id: "PCM-LAB-SP-INSTALL-001",
      kind: "labor",
      category: "音響",
      genre: "音響",
      name: "スピーカー取付・配線工事",
      costPrice: null,
      sellPrice: 16000,
      unitLabel: "式",
      notes: "天井埋込2台までの標準",
      tags: ["音響", "取付"],
    },
    {
      id: "PCM-LAB-IOT-PANEL-001",
      kind: "labor",
      category: "IOT関連",
      genre: "IOT関連",
      name: "IoT盤組立・初期設定",
      costPrice: null,
      sellPrice: 28000,
      unitLabel: "式",
      notes: "ESP32/RP2350 盤組・通信確認",
      tags: ["IOT関連", "盤", "設定"],
    },
  ];
